#!/bin/bash

# Check if an argument is provided
if [ -z "$1" ]; then
  # No argument provided, print usage and exit
  echo "This script unzips most of the .tar.gz files present in subfolder 'zipped' into a target directory."
  echo "If the target directory already exists, the script will exit without doing anything. Otherwise, it will be created."
  echo "Usage: $0 <target_directory_name>"
  echo "Example: '$0 ../sources' will create a directory 'sources' next to this directory ('zipped'), and will extract the files into it."
  echo "No target directory name was specified. Existing."
  exit 1
fi

# Command-line argument was provided, use it as the directory name
directory_name="$1"

# Check if the directory already exists
if [ -d "$directory_name" ]; then
  echo "Target directory '$directory_name' already exists. Will not overwrite it. Please delete it, or choose a different name. Exiting."
  exit 1
fi

# Create the directory
mkdir --parents "$directory_name"

# Check if the directory creation was successful
if [ $? -eq 0 ]; then
  echo "Target directory '$directory_name' created successfully."
else
  echo "Error: Failed to create directory '$directory_name'. Exiting."
  exit 1
fi

# Abort the script on the 1st encountered error, if any:
set -e

# Print each command:
set -o xtrace

# Manually create this Makefile. We found it in android-1.6_r1 (the oldest android tag in AOSP):
printf "### DO NOT EDIT THIS FILE ###\ninclude build/core/main.mk\n### DO NOT EDIT THIS FILE ###\n" > "$directory_name/Makefile"

# Note: this script works even with older tar versions (below v1.28 ,pre-year-2014);
# they don't support the "--one-top-level=..." option, hence we use a separate "mkdir" command to create each target folder.

mkdir --parents "$directory_name/bionic"
tar -xzvf bionic-a27d2baa0c1a2ec70f47ea9199b1dd6762c8a349.tar.gz -C "$directory_name/bionic"

mkdir --parents "$directory_name/bootable/recovery"
tar -xzvf recovery-23580ca27a0a8109312fdd36cc363ad1f4719889.tar.gz -C "$directory_name/bootable/recovery"

mkdir --parents "$directory_name/bootable/bootloader/legacy"
tar -xzvf legacy-4205b865141ff2e255fe1d3bd16de18e217ef06a.tar.gz -C "$directory_name/bootable/bootloader/legacy"

mkdir --parents "$directory_name/build"
tar -xzvf build.git-b6c1cf6de79035f58b512f4400db458c8401379a.tar.gz -C "$directory_name/build"

mkdir --parents "$directory_name/dalvik"
tar -xzvf dalvik.git-2ad60cfc28e14ee8f0bb038720836a4696c478ad.tar.gz -C "$directory_name/dalvik"

mkdir --parents "$directory_name/development"
tar -xzvf development-5c11852110eeb03dc5a69111354b383f98d15336.tar.gz -C "$directory_name/development"

mkdir --parents "$directory_name/external/aes"
tar -xzvf aes-045e5c3c0c0154d54e7abd95bf6505ddfff27dee.tar.gz -C "$directory_name/external/aes"

mkdir --parents "$directory_name/external/apache-http"
tar -xzvf apache-http-417f3b92ba4549b2f22340e3107d869d2b9c5bb8.tar.gz -C "$directory_name/external/apache-http"

mkdir --parents "$directory_name/external/bluez"
tar -xzvf bluez-611c26d196ef15425ae92dec9f3cdf92bbbe489a.tar.gz -C "$directory_name/external/bluez"

mkdir --parents "$directory_name/external/clearsilver"
tar -xzvf clearsilver-5287bd68df69562fb14b988db841dd45b549e328.tar.gz -C "$directory_name/external/clearsilver"

mkdir --parents "$directory_name/external/dbus"
tar -xzvf dbus-7b0daf50cdb48a342490b35b83d80f80ee71915a.tar.gz -C "$directory_name/external/dbus"

mkdir --parents "$directory_name/external/dhcpcd"
tar -xzvf dhcpcd-e95877ecfa1170d77b1ec1f66752725cdda01b64.tar.gz -C "$directory_name/external/dhcpcd"

mkdir --parents "$directory_name/external/dropbear"
tar -xzvf dropbear-98b10356d53e48ffa482d72a36ec267ae5ea1dcc.tar.gz -C "$directory_name/external/dropbear"

mkdir --parents "$directory_name/external/elfcopy"
tar -xzvf elfcopy-130444ec10d2a40e2b3ede4863ab005aa1f4580c.tar.gz -C "$directory_name/external/elfcopy"

mkdir --parents "$directory_name/external/elfutils"
tar -xzvf elfutils-593c365a822e505dae3aaa4d8d66eca333911624.tar.gz -C "$directory_name/external/elfutils"

mkdir --parents "$directory_name/external/emma"
tar -xzvf emma-a0c5294bd396e480cbf850bde283a94042526698.tar.gz -C "$directory_name/external/emma"

mkdir --parents "$directory_name/external/esd"
tar -xzvf esd-53f215a8fd2333401e6ebc681581ad335726a0a7.tar.gz -C "$directory_name/external/esd"

mkdir --parents "$directory_name/external/expat"
tar -xzvf expat-8a666ab336063fc53e446702fdf9ffe14af69e71.tar.gz -C "$directory_name/external/expat"

mkdir --parents "$directory_name/external/fdlibm"
tar -xzvf fdlibm-8771baa10b2dc5bbedb08231d99c72cfd6abcb5b.tar.gz -C "$directory_name/external/fdlibm"

mkdir --parents "$directory_name/external/freetype"
tar -xzvf freetype-a38fc482eeeb2c1929803c233835369dcf1b8781.tar.gz -C "$directory_name/external/freetype"

mkdir --parents "$directory_name/external/gdata"
tar -xzvf gdata-27eda2eccd3729366a5545a21238ee9b2960171c.tar.gz -C "$directory_name/external/gdata"

mkdir --parents "$directory_name/external/giflib"
tar -xzvf giflib-56f1b66a4b20a7f85865c852dd46df5e4635a9d6.tar.gz -C "$directory_name/external/giflib"

mkdir --parents "$directory_name/external/googleclient"
tar -xzvf googleclient-0dc808d29e2df4178f51efb62ecb32656f1533ad.tar.gz -C "$directory_name/external/googleclient"

mkdir --parents "$directory_name/external/icu4c"
tar -xzvf icu4c-43ebef775dab9dd52bc39eb98f306be1b3adbc8a.tar.gz -C "$directory_name/external/icu4c"

mkdir --parents "$directory_name/external/iptables"
tar -xzvf iptables-15630edb6b7f5ba40c572c43db13342243c23f10.tar.gz -C "$directory_name/external/iptables"

mkdir --parents "$directory_name/external/jdiff"
tar -xzvf jdiff-4e6c94bfd678c59b66cd39cef53193ed83a17d08.tar.gz -C "$directory_name/external/jdiff"

mkdir --parents "$directory_name/external/jhead"
tar -xzvf jhead-426377d9ce95606bac741d99b5b0a3e2038924fe.tar.gz -C "$directory_name/external/jhead"

mkdir --parents "$directory_name/external/jpeg"
tar -xzvf jpeg-d9bb1510bee7d9bf2a0f2699c647a65e67ab9cf8.tar.gz -C "$directory_name/external/jpeg"

mkdir --parents "$directory_name/external/libffi"
tar -xzvf libffi-056e203a7aec4c87c077192ad776b532a3d0305f.tar.gz -C "$directory_name/external/libffi"

mkdir --parents "$directory_name/external/libpcap"
tar -xzvf libpcap-858aa678df9736fefabc0671973c0f58dc246f91.tar.gz -C "$directory_name/external/libpcap"

mkdir --parents "$directory_name/external/libpng"
tar -xzvf libpng-368f3c41d0e7f802a92a59a342c6ae37d212743d.tar.gz -C "$directory_name/external/libpng"

mkdir --parents "$directory_name/external/libxml2"
tar -xzvf libxml2-6e8825d5c6462dd394226dbd7b193f95b40c4f22.tar.gz -C "$directory_name/external/libxml2"

mkdir --parents "$directory_name/external/netcat"
tar -xzvf netcat-446d5a68930e2dbab2a9b2ab7d9f4fd5a7bd7419.tar.gz -C "$directory_name/external/netcat"

mkdir --parents "$directory_name/external/netperf"
tar -xzvf netperf-95f43f4cdc93396b513e017be8d1c7cc5bf846ef.tar.gz -C "$directory_name/external/netperf"

mkdir --parents "$directory_name/external/neven"
tar -xzvf neven-30957f56b33a18c5a4af787f25b9f145f2803634.tar.gz -C "$directory_name/external/neven"

mkdir --parents "$directory_name/external/opencore"
tar -xzvf opencore-e4e1fdb450347fcb33f19e8a5c2f3f2cb2645967.tar.gz -C "$directory_name/external/opencore"

mkdir --parents "$directory_name/external/openssl"
tar -xzvf openssl-f48372ded3bb76c2598392aa58abe6e2eb7432d2.tar.gz -C "$directory_name/external/openssl"

mkdir --parents "$directory_name/external/oprofile"
tar -xzvf oprofile-48ae5fc270ea3bbb965b4bd07cb1691a5c115642.tar.gz -C "$directory_name/external/oprofile"

mkdir --parents "$directory_name/external/ping"
tar -xzvf ping-315013e18c06adca06f23be9bc6556fbd22f0c87.tar.gz -C "$directory_name/external/ping"

mkdir --parents "$directory_name/external/ppp"
tar -xzvf ppp-dab68864983c4a0c6ef9e6d7e5834472c4c75f9c.tar.gz -C "$directory_name/external/ppp"

mkdir --parents "$directory_name/external/protobuf"
tar -xzvf protobuf-35be73bfebdd5cf76922b2a44b15ebbbeaa8d079.tar.gz -C "$directory_name/external/protobuf"

mkdir --parents "$directory_name/external/qemu"
tar -xzvf qemu-55f4e4a5ec657a017e3bf75299ad71fd1c968dd3.tar.gz -C "$directory_name/external/qemu"

mkdir --parents "$directory_name/external/safe-iop"
tar -xzvf safe-iop-a09f917d93140479fd7964892dd38d3a86c42b7a.tar.gz -C "$directory_name/external/safe-iop"

mkdir --parents "$directory_name/external/skia"
tar -xzvf skia-262917823441f183fa67aa63b9c0ec4e52cce4c3.tar.gz -C "$directory_name/external/skia"

mkdir --parents "$directory_name/external/sonivox"
tar -xzvf sonivox-e442bb7cd6a085b33a4dd52c0e20a157ada7feb1.tar.gz -C "$directory_name/external/sonivox"

mkdir --parents "$directory_name/external/sqlite"
tar -xzvf sqlite-6005ac625aa553fe461b363385a8ed4a3c217a1f.tar.gz -C "$directory_name/external/sqlite"

mkdir --parents "$directory_name/external/srec"
tar -xzvf srec-8fc5a7f51e62cb4ae44a27bdf4176d04adc80ede.tar.gz -C "$directory_name/external/srec"

mkdir --parents "$directory_name/external/strace"
tar -xzvf strace-4a3ec90c3aa1cecc489f6fd19d785c6473ee8164.tar.gz -C "$directory_name/external/strace"

mkdir --parents "$directory_name/external/tagsoup"
tar -xzvf tagsoup-926d907a2fb69573f1c6337f064645dde18b1e5e.tar.gz -C "$directory_name/external/tagsoup"

mkdir --parents "$directory_name/external/tcpdump"
tar -xzvf tcpdump-9799c4b4d38c4aa2acc7ec7d593983bd178e49f6.tar.gz -C "$directory_name/external/tcpdump"

mkdir --parents "$directory_name/external/tinyxml"
tar -xzvf tinyxml-09457b6e6c51b981b61a99a2157e0b3dd4bea444.tar.gz -C "$directory_name/external/tinyxml"

mkdir --parents "$directory_name/external/tremor"
tar -xzvf tremor-28350ca441529b0f17844a39e2fc1b63ea7d83ef.tar.gz -C "$directory_name/external/tremor"

mkdir --parents "$directory_name/external/webkit"
tar -xzvf webkit-9364f22aed35e1a1e9d07c121510f80be3ab0502.tar.gz -C "$directory_name/external/webkit"

mkdir --parents "$directory_name/external/wpa_supplicant"
tar -xzvf wpa_supplicant-ef98df019e941b9a51686e89495c16b4ead23140.tar.gz -C "$directory_name/external/wpa_supplicant"

mkdir --parents "$directory_name/external/yaffs2"
tar -xzvf yaffs2-85ff57da47aaa93dc0018940cbd6b1f923664b46.tar.gz -C "$directory_name/external/yaffs2"

mkdir --parents "$directory_name/external/zlib"
tar -xzvf zlib-edc3fb3b9f9250ceacaf07a83beb5dde02807f9c.tar.gz -C "$directory_name/external/zlib"

mkdir --parents "$directory_name/frameworks/base"
tar -xzvf base-54b6cfa9a9e5b861a9930af873580d6dc20f773c.tar.gz -C "$directory_name/frameworks/base"

mkdir --parents "$directory_name/platform/frameworks/opt/com.google.android"
tar -xzvf com.google.android-19915d13a476d1dc054db396c1c755507fa43a42.tar.gz -C "$directory_name/platform/frameworks/opt/com.google.android"

mkdir --parents "$directory_name/platform/frameworks/opt/com.google.android.googlelogin"
tar -xzvf com.google.android.googlelogin-844632d1ca7c49ad62b8a09f7d735712c416e3d3.tar.gz -C "$directory_name/platform/frameworks/opt/com.google.android.googlelogin"

mkdir --parents "$directory_name/frameworks/policies/base"
tar -xzvf base-58096b60fc111564c663d685d3b147ea4a5f3832.tar.gz -C "$directory_name/frameworks/policies/base"

mkdir --parents "$directory_name/hardware/libhardware"
tar -xzvf libhardware-d6054a36475b5ff502b4af78f7d272a713c1a8e7.tar.gz -C "$directory_name/hardware/libhardware"

mkdir --parents "$directory_name/hardware/ril"
tar -xzvf ril-dbbb392e15b5ace6f19e76c49c80ea14292e8a4d.tar.gz -C "$directory_name/hardware/ril"

mkdir --parents "$directory_name/kernel"
tar -xzvf msm-4b119e21d0c66c22e8ca03df05d9de623d0eb50f.tar.gz -C "$directory_name/kernel"

mkdir --parents "$directory_name/packages/apps/AlarmClock"
tar -xzvf AlarmClock-291e1a50b41a6ae47eddb1713dc99d22f96d0c9f.tar.gz -C "$directory_name/packages/apps/AlarmClock"

mkdir --parents "$directory_name/packages/apps/Browser"
tar -xzvf Browser-ba6d7b853c32ad6c3be26c443daa61f322bcfdc2.tar.gz -C "$directory_name/packages/apps/Browser"

mkdir --parents "$directory_name/packages/apps/Calculator"
tar -xzvf Calculator-979004c651c1dc2327c4d74688cbaa5cbb9f08e1.tar.gz -C "$directory_name/packages/apps/Calculator"

mkdir --parents "$directory_name/packages/apps/Calendar"
tar -xzvf Calendar-a390cbfd25a5f3b2f002df725b7580bc78bd9edf.tar.gz -C "$directory_name/packages/apps/Calendar"

mkdir --parents "$directory_name/packages/apps/Camera"
tar -xzvf Camera-1d4c75065966c4f6f56900e31f655bfd1b334435.tar.gz -C "$directory_name/packages/apps/Camera"

mkdir --parents "$directory_name/packages/apps/Contacts"
tar -xzvf Contacts-5dc3b4f80f38c0d48601f66c2c0e551474a7f8ad.tar.gz -C "$directory_name/packages/apps/Contacts"

mkdir --parents "$directory_name/packages/apps/Email"
tar -xzvf Email-8978aac1977408b05e386ae846c30920c7faa0a6.tar.gz -C "$directory_name/packages/apps/Email"

mkdir --parents "$directory_name/packages/apps/GoogleSearch"
tar -xzvf GoogleSearch-c398e48938ffaa5ff8db0de81a54a4952e26394f.tar.gz -C "$directory_name/packages/apps/GoogleSearch"

mkdir --parents "$directory_name/packages/apps/HTMLViewer"
tar -xzvf HTMLViewer-dbdb2a036901f82d3bb27e35a8140206da2328dd.tar.gz -C "$directory_name/packages/apps/HTMLViewer"

mkdir --parents "$directory_name/packages/apps/IM"
tar -xzvf IM-4879f9aa9a3ba8ea89fe31f8d765c4908d4fd53a.tar.gz -C "$directory_name/packages/apps/IM"

mkdir --parents "$directory_name/packages/apps/Launcher"
tar -xzvf Launcher-c8f00b61c600927ab404c84686d4472e9b527976.tar.gz -C "$directory_name/packages/apps/Launcher"

mkdir --parents "$directory_name/packages/apps/Mms"
tar -xzvf Mms-8eed706474910ccb978acda03e85d3261037da6e.tar.gz -C "$directory_name/packages/apps/Mms"

mkdir --parents "$directory_name/packages/apps/Music"
tar -xzvf Music-6cb8bc92e0ca524a76a6fa3f6814b43ea9a3b30d.tar.gz -C "$directory_name/packages/apps/Music"

mkdir --parents "$directory_name/packages/apps/PackageInstaller"
tar -xzvf PackageInstaller-088073e6787fca4bfc68d6b04a5e887a03faf745.tar.gz -C "$directory_name/packages/apps/PackageInstaller"

mkdir --parents "$directory_name/packages/apps/Phone"
tar -xzvf Phone-abc47110c17fa8e8cb6161bc045e87f31eeb7a1c.tar.gz -C "$directory_name/packages/apps/Phone"

mkdir --parents "$directory_name/packages/apps/Settings"
tar -xzvf Settings-de2d9f5f109265873196f1615e1f3546b114aaa7.tar.gz -C "$directory_name/packages/apps/Settings"

mkdir --parents "$directory_name/packages/apps/SoundRecorder"
tar -xzvf SoundRecorder-e2118f54af4c5215bd988979769e383292b9c9cb.tar.gz -C "$directory_name/packages/apps/SoundRecorder"

mkdir --parents "$directory_name/packages/apps/Stk"
tar -xzvf Stk-e405ce157d5bfb44efa33a314ae08d543bc9d39e.tar.gz -C "$directory_name/packages/apps/Stk"

mkdir --parents "$directory_name/packages/apps/Sync"
tar -xzvf Sync-79d30fe428c6dae46ae66afeb9d5c5f6ae34ddeb.tar.gz -C "$directory_name/packages/apps/Sync"

mkdir --parents "$directory_name/packages/apps/Updater"
tar -xzvf Updater-5fad77410b4e940237533bb8a0d306db36be0a23.tar.gz -C "$directory_name/packages/apps/Updater"

mkdir --parents "$directory_name/packages/apps/VoiceDialer"
tar -xzvf VoiceDialer-22464da53983813d22e37d9656e8cbd7809e9ebf.tar.gz  -C "$directory_name/packages/apps/VoiceDialer"

mkdir --parents "$directory_name/packages/providers/CalendarProvider"
tar -xzvf CalendarProvider-b558dececce20291e0a0195a4bd9835f4a8a1918.tar.gz -C "$directory_name/packages/providers/CalendarProvider"

mkdir --parents "$directory_name/packages/providers/ContactsProvider"
tar -xzvf ContactsProvider-0f58cfe01bb0f491330f7dcf85d54d0081459b57.tar.gz -C "$directory_name/packages/providers/ContactsProvider"

mkdir --parents "$directory_name/packages/providers/DownloadProvider"
tar -xzvf DownloadProvider-57f55b3cb4f7e4136cde8d1ea12c1e70ec903362.tar.gz -C "$directory_name/packages/providers/DownloadProvider"

mkdir --parents "$directory_name/packages/providers/DrmProvider"
tar -xzvf DrmProvider-6b8295c9350c603bdd930a29a877c8e95f4641ac.tar.gz -C "$directory_name/packages/providers/DrmProvider"

mkdir --parents "$directory_name/packages/providers/GoogleContactsProvider"
tar -xzvf GoogleContactsProvider-7251cb2492beceb08520bade25df701508246914.tar.gz -C "$directory_name/packages/providers/GoogleContactsProvider"

mkdir --parents "$directory_name/packages/providers/GoogleSubscribedFeedsProvider"
tar -xzvf GoogleSubscribedFeedsProvider-f0d44cd75cfa07df3c9162bc2a03884c21a7fb8f.tar.gz -C "$directory_name/packages/providers/GoogleSubscribedFeedsProvider"

mkdir --parents "$directory_name/packages/providers/ImProvider"
tar -xzvf ImProvider-ef4989eb3bd594f384dd24ac3b2e7e13e180a026.tar.gz -C "$directory_name/packages/providers/ImProvider"

mkdir --parents "$directory_name/packages/providers/MediaProvider"
tar -xzvf MediaProvider-b80ba9251102fc785a5f231f41a61af1781723a2.tar.gz -C "$directory_name/packages/providers/MediaProvider"

mkdir --parents "$directory_name/packages/providers/TelephonyProvider"
tar -xzvf TelephonyProvider-15fe736a6429ed6e4cc0138ce88b241807af207e.tar.gz -C "$directory_name/packages/providers/TelephonyProvider"

mkdir --parents "$directory_name/prebuilt"
tar -xzvf prebuilt-e7214a75e616f54c5de3b38bfceae11ee5f1b9eb.tar.gz -C "$directory_name/prebuilt"

mkdir --parents "$directory_name/system/bluetooth"
tar -xzvf bluetooth-6c2d13d0c3a4505fdac56ae8d537a68218e072f1.tar.gz -C "$directory_name/system/bluetooth"

mkdir --parents "$directory_name/system/core"
tar -xzvf core-4f6e8d7a00cbeda1e70cc15be9c4af1018bdad53.tar.gz -C "$directory_name/system/core"

mkdir --parents "$directory_name/system/extras"
tar -xzvf extras-7341494707810f709855ea85ce03a8ec3ac8dbaf.tar.gz -C "$directory_name/system/extras"

mkdir --parents "$directory_name/system/wlan/ti"
tar -xzvf ti-607e8a019b921eee008cd1e9ffc132318fabce7f.tar.gz -C "$directory_name/system/wlan/ti"

# This is a symlink that points to /tmp/bionic-kernel-headers/asm-arm ; it is useless, since the destination files don't exist. Delete it:
rm "$directory_name/bionic/libc/arch-arm/include/asm"

# Fix for the following build error: 
#frameworks/base/libs/surfaceflinger/SurfaceFlinger.cpp:1592: error: ‘INT_MAX’ was not declared in this scope
# It inserts a new line "#include <limits.h>" at line 22:
sed -i '22 i #include <limits.h>' "$directory_name/frameworks/base/libs/surfaceflinger/SurfaceFlinger.cpp"

printf "\nAll done, enjoy!\n"
exit 0

